### ISSUE TITLE
hasRoleOrRestrict throwing "Too many arguments for 'find' method on Buzzard

### ISSUE THREAD

**Issue by gsavoie** [feathersjs-ecosystem/feathers-authentication-hooks#41]
Hello,

I don't know if `feathers-authentication-hooks` is supposed to support Feathersjs Buzzard (v3) but it seems like I could not get `hasRoleOrRestrict` to work.

See this stack
```
error:  Error: Too many arguments for 'find' method
    at validateArguments (C:\code\daytrade\server\node_modules\@feathersjs\commons\lib\arguments.js:24:11)
    at Object.validateHook (C:\code\daytrade\server\node_modules\@feathersjs\feathers\lib\hooks.js:48:9)
    at promise.then.hookObject (C:\code\daytrade\server\node_modules\@feathersjs\commons\lib\hooks.js:174:73)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error:  NotFound: No record found
    at new NotFound (C:\code\daytrade\server\node_modules\feathers-errors\lib\index.js:121:17)
    at C:\code\daytrade\server\node_modules\feathers-authentication-hooks\lib\has-role-or-restrict.js:141:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Apparently there is now a validation for the number of arguments (find is limited to 1), see
https://github.com/feathersjs/commons/blob/master/lib/arguments.js#L24

And in `hasRoleOrRestrict` we pass two arguments to find, see
https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/master/src/has-role-or-restrict.js#L134

Should we just merge the params? I tried something like `hook.service.find({ ...params, query })` and it seemed to work... 

If you think it's a good solution, let me know I can open a PR and fix the tests, just unsure what's the support on Buzzard and the impacts of this change.

**Comment by daffl** [comment]
Yes, it should be `Object.assign({}, params, { query })`. I don't believe this ever worked as intended.

**Comment by gsavoie** [comment]
Thanks @daffl, opened a PR.
